name: fcf_messaging
description: Flutter/Cloud Firestore messaging app.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.12.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.0+1
  contacts_service: ^0.3.10
  cupertino_icons: ^0.1.3
  equatable: ^1.0.3
  email_validator: ^1.0.4
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+3
  firebase_lumberdash: ^2.1.0
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.1.1
  flushbar: ^1.9.1
  flutter_auth_buttons: ^0.6.0
  flutter_bloc: ^3.2.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^4.1.1+1
  get_it: ^3.1.0
  google_sign_in: ^4.1.1
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  intl: ^0.16.0
  lumberdash: ^2.1.1
  meta: ^1.1.8
  password_strength: ^0.1.2
  path_provider: ^1.6.0
  permission_handler: '^4.2.0+hotfix.3'
  # responsive_builder: ^0.1.4
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+1

dev_dependencies:
  bloc_test: ^3.1.0
  build_runner:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  intl_translation: ^0.17.9
  mockito: ^4.1.1
  pedantic: ^1.8.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: #FFFFFF

flutter:
  uses-material-design: true
  assets:
    - assets/images/